name: Update Docs

on:
  push:
    branches: [main]

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: gh-pages

    - name: Create environment
      run: python -m venv env

    - name: Generate Docs
      run: |
        source env/bin/activate
        python --version
        root=$PWD
        ls
        cd /tmp
        git clone https://github.com/vsoch/elfcall
        cd elfcall
        pip install -e .
        cd docs
        pip install -r requirements.txt
        make html
        mv $root/.git _build/html/.git
        rm -rf $root
        mv _build/html $root
        cd $root
        touch .nojekyll
        ls

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@ba1486788b0490a235422264426c45848eac35c6 # v4.4.1
      with:
        branch: gh-pages
        folder: .
